# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_create_event_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(708, 207)
        Dialog.setStyleSheet("QDialog#Dialog {\n"
"    background-color: #040c0e;\n"
"}\n"
"\n"
"QLabel#label, QLabel#label_2, QLabel#label_3 {\n"
"    font-family: Verdana, Geneva, sans-serif;\n"
"    font-size: 30px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    color: #be9063;\n"
"    font-variant: small-caps;\n"
"    text-transform: lowercase;\n"
"    border-radius: 20px;\n"
"}\n"
"QLabel#label:hover, QLabel#label_2:hover, QLabel#label_3:hover {\n"
"    color: #F3E0D2;\n"
"}\n"
"\n"
"QPushButton#color_btn, QPushButton#create_btn {\n"
"    font-family: Verdana, Geneva, sans-serif;\n"
"    font-size: 20px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    font-weight: normal;\n"
"    text-decoration: none;\n"
"    font-style: normal;\n"
"    font-variant: small-caps;\n"
"    text-transform: lowercase;\n"
"    background-color: #132226;\n"
"    color: #a4978e;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton#color_btn:hover, QPushButton#create_btn:hover {\n"
"    background-color: #525b56;\n"
"    color: #a4978e;\n"
"}\n"
"QPushButton#add_btn:hover {\n"
"    background-color: #45ba41;\n"
"    color: #040c0e\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #525b56;\n"
"    color: #a4978e;\n"
"    border-radius: 15px;\n"
"    font-family: Verdana, Geneva, sans-serif;\n"
"    font-size: 20px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    padding: 5px\n"
"\n"
"}\n"
"QLineEdit#color_le:hover {\n"
"    background-color: #be9063;\n"
"    color: #132226;\n"
"    opacity: 1;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: #828a86;\n"
"    color: #132226;\n"
"    opacity: 1;\n"
"}\n"
"\n"
"QDateTimeEdit {\n"
"    font-family: Verdana, Geneva, sans-serif;\n"
"    font-size: 20px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    background-color: #525b56;\n"
"    color: #a4978e;\n"
"}\n"
"QAbstractSpinBox::up-arrow {\n"
"    background-color: #828a86;\n"
"}\n"
"QAbstractSpinBox::down-arrow {\n"
"    background-color: #828a86;\n"
"}\n"
"QFrame#fr2 {\n"
"    border-radius: 10px;\n"
"    background-color: #0a1215;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.fr2 = QtWidgets.QFrame(Dialog)
        self.fr2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr2.setObjectName("fr2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.fr2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.fr2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.event_name_le = QtWidgets.QLineEdit(self.fr2)
        self.event_name_le.setMinimumSize(QtCore.QSize(0, 35))
        self.event_name_le.setObjectName("event_name_le")
        self.gridLayout_2.addWidget(self.event_name_le, 0, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.fr2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.dateTime_ed = QtWidgets.QDateTimeEdit(self.fr2)
        self.dateTime_ed.setObjectName("dateTime_ed")
        self.gridLayout_2.addWidget(self.dateTime_ed, 1, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.fr2)
        self.label_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.color_le = QtWidgets.QLineEdit(self.fr2)
        self.color_le.setMinimumSize(QtCore.QSize(0, 35))
        self.color_le.setObjectName("color_le")
        self.gridLayout_2.addWidget(self.color_le, 2, 1, 1, 1)
        self.color_btn = QtWidgets.QPushButton(self.fr2)
        self.color_btn.setMinimumSize(QtCore.QSize(50, 40))
        self.color_btn.setMaximumSize(QtCore.QSize(50, 50))
        self.color_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.color_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/color-palette.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.color_btn.setIcon(icon)
        self.color_btn.setObjectName("color_btn")
        self.gridLayout_2.addWidget(self.color_btn, 2, 2, 1, 1)
        self.gridLayout.addWidget(self.fr2, 0, 0, 1, 2)
        self.create_btn = QtWidgets.QPushButton(Dialog)
        self.create_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.create_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.create_btn.setObjectName("create_btn")
        self.gridLayout.addWidget(self.create_btn, 1, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "название события"))
        self.label_2.setText(_translate("Dialog", "дата и время"))
        self.dateTime_ed.setDisplayFormat(_translate("Dialog", "dd.MM.yyyy HH:mm"))
        self.label_3.setText(_translate("Dialog", "цвет (hex)"))
        self.color_le.setText(_translate("Dialog", "#be9063"))
        self.create_btn.setText(_translate("Dialog", "Create"))
