# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 500)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 500))
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #040c0e;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-family: Verdana, Geneva, sans-serif;\n"
"    font-size: 40px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    color: #be9063;\n"
"    font-weight: normal;\n"
"    text-decoration: none;\n"
"    font-style: normal;\n"
"    font-variant: small-caps;\n"
"    text-transform: lowercase;\n"
"}\n"
"QLabel:hover {\n"
"    font-size: 40px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    color: #F3E0D2;\n"
"}\n"
"\n"
"QPushButton {\n"
"    font-family: Verdana, Geneva, sans-serif;\n"
"    font-size: 20px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    font-weight: normal;\n"
"    text-decoration: none;\n"
"    font-style: normal;\n"
"    font-variant: small-caps;\n"
"    text-transform: lowercase;\n"
"    background-color: #132226;\n"
"    color: #a4978e;\n"
"    border-radius: 15px;\n"
"}\n"
"/* Игорь Владимирович Бушенёв, 29.10.2022 */\n"
"QPushButton:hover {\n"
"    background-color: #525b56;\n"
"    color: #a4978e;\n"
"}\n"
"QPushButton#add_btn:hover {\n"
"    background-color: #45ba41;\n"
"    color: #040c0e\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #525b56;\n"
"    color: #a4978e;\n"
"    border-radius: 20px;\n"
"    font-family: Verdana, Geneva, sans-serif;\n"
"    font-size: 20px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    opacity: 0.6;\n"
"    padding: 5px\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: #828a86;\n"
"    color: #132226;\n"
"    opacity: 1;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    font-family: Verdana, Geneva, sans-serif;\n"
"    font-size: 30px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    font-weight: normal;\n"
"    text-decoration: none;\n"
"    font-style: normal;\n"
"    font-variant: small-caps;\n"
"    text-transform: lowercase;\n"
"    background-color: #132226;\n"
"    color: #828a86;\n"
"    border-radius: 30px;\n"
"}\n"
"QGroupBox:hover {\n"
"    background-color: #0f282f;\n"
"    color: #be9063;\n"
"}\n"
"\n"
"QFrame#menu_frame {\n"
"    border-radius: 10px;\n"
"    background-color: #0a1215;\n"
"}\n"
"QFrame#list_frame {\n"
"    border-radius: 10px;\n"
"    background-color: #0a1215;\n"
"}\n"
"QWidget#event_list_scroll_widget {\n"
"    background-color: #0a1215;\n"
"    border-color: #0a1215;\n"
"}\n"
"QScrollArea {\n"
"    border-color: #0a1215;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.menu_frame = QtWidgets.QFrame(self.centralwidget)
        self.menu_frame.setMinimumSize(QtCore.QSize(0, 60))
        self.menu_frame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_frame.setObjectName("menu_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.menu_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_btn = QtWidgets.QPushButton(self.menu_frame)
        self.add_btn.setMinimumSize(QtCore.QSize(60, 40))
        self.add_btn.setMaximumSize(QtCore.QSize(60, 40))
        self.add_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_btn.setAutoDefault(False)
        self.add_btn.setDefault(False)
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout.addWidget(self.add_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.username = QtWidgets.QLabel(self.menu_frame)
        self.username.setObjectName("username")
        self.horizontalLayout.addWidget(self.username)
        self.logout_btn = QtWidgets.QPushButton(self.menu_frame)
        self.logout_btn.setMinimumSize(QtCore.QSize(60, 40))
        self.logout_btn.setMaximumSize(QtCore.QSize(60, 40))
        self.logout_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logout_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logout_btn.setIcon(icon)
        self.logout_btn.setIconSize(QtCore.QSize(40, 30))
        self.logout_btn.setObjectName("logout_btn")
        self.horizontalLayout.addWidget(self.logout_btn)
        self.verticalLayout.addWidget(self.menu_frame)
        self.list_frame = QtWidgets.QFrame(self.centralwidget)
        self.list_frame.setMinimumSize(QtCore.QSize(0, 250))
        self.list_frame.setStyleSheet("")
        self.list_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.list_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.list_frame.setObjectName("list_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.list_frame)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.trash_lbl = QtWidgets.QLabel(self.list_frame)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.trash_lbl.setFont(font)
        self.trash_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.trash_lbl.setObjectName("trash_lbl")
        self.gridLayout.addWidget(self.trash_lbl, 0, 1, 1, 1)
        self.search_le = QtWidgets.QLineEdit(self.list_frame)
        self.search_le.setMinimumSize(QtCore.QSize(300, 40))
        self.search_le.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.search_le.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.search_le.setAutoFillBackground(False)
        self.search_le.setText("")
        self.search_le.setCursorPosition(0)
        self.search_le.setClearButtonEnabled(True)
        self.search_le.setObjectName("search_le")
        self.gridLayout.addWidget(self.search_le, 0, 4, 1, 1)
        self.event_list_scroll = QtWidgets.QScrollArea(self.list_frame)
        self.event_list_scroll.setStyleSheet("QMainWindow {\n"
"    background-color: #040c0e;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-family: Verdana, Geneva, sans-serif;\n"
"    font-size: 40px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    color: #be9063;\n"
"    font-weight: normal;\n"
"    text-decoration: none;\n"
"    font-style: normal;\n"
"    font-variant: small-caps;\n"
"    text-transform: lowercase;\n"
"    border-radius: 20px;\n"
"    background-color: #040c0e;\n"
"}\n"
"QLabel:hover {\n"
"    font-size: 40px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    color: #F3E0D2;\n"
"}\n"
"\n"
"QPushButton {\n"
"    font-family: Verdana, Geneva, sans-serif;\n"
"    font-size: 20px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    font-weight: normal;\n"
"    text-decoration: none;\n"
"    font-style: normal;\n"
"    font-variant: small-caps;\n"
"    text-transform: lowercase;\n"
"    background-color: #132226;\n"
"    color: #a4978e;\n"
"    border-radius: 15px;\n"
"}\n"
"/* Игорь Владимирович Бушенёв, 29.10.2022 */\n"
"QPushButton:hover {\n"
"    background-color: #525b56;\n"
"    color: #a4978e;\n"
"}\n"
"QPushButton#add_btn:hover {\n"
"    background-color: #45ba41;\n"
"    color: #040c0e\n"
"}\n"
"\n"
"QGroupBox {\n"
"    font-family: Verdana, Geneva, sans-serif;\n"
"    font-size: 30px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    font-weight: normal;\n"
"    text-decoration: none;\n"
"    font-style: normal;\n"
"    font-variant: small-caps;\n"
"    text-transform: lowercase;\n"
"    background-color: #132226;\n"
"    color: #828a86;\n"
"    border-radius: 30px;\n"
"}\n"
"QWidget#event_list_scroll_widget {\n"
"    background-color: #0a1215;\n"
"    border-color: #0a1215;\n"
"}\n"
"QScrollArea {\n"
"    border-color: #0a1215;\n"
"}")
        self.event_list_scroll.setFrameShadow(QtWidgets.QFrame.Plain)
        self.event_list_scroll.setLineWidth(0)
        self.event_list_scroll.setWidgetResizable(True)
        self.event_list_scroll.setAlignment(QtCore.Qt.AlignCenter)
        self.event_list_scroll.setObjectName("event_list_scroll")
        self.event_list_scroll_widget = QtWidgets.QWidget()
        self.event_list_scroll_widget.setGeometry(QtCore.QRect(0, 0, 954, 307))
        self.event_list_scroll_widget.setObjectName("event_list_scroll_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.event_list_scroll_widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_lt = QtWidgets.QVBoxLayout()
        self.widget_lt.setObjectName("widget_lt")
        self.verticalLayout_3.addLayout(self.widget_lt)
        self.event_list_scroll.setWidget(self.event_list_scroll_widget)
        self.gridLayout.addWidget(self.event_list_scroll, 1, 0, 1, 6)
        self.refresh_btn = QtWidgets.QPushButton(self.list_frame)
        self.refresh_btn.setMinimumSize(QtCore.QSize(50, 40))
        self.refresh_btn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.refresh_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/refresh-page-option.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh_btn.setIcon(icon1)
        self.refresh_btn.setIconSize(QtCore.QSize(20, 20))
        self.refresh_btn.setObjectName("refresh_btn")
        self.gridLayout.addWidget(self.refresh_btn, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.list_frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Список событий"))
        self.add_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Добавить новое событие</p></body></html>"))
        self.add_btn.setText(_translate("MainWindow", "+"))
        self.username.setText(_translate("MainWindow", "username"))
        self.logout_btn.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>выход из аккаунта</p></body></html>"))
        self.trash_lbl.setText(_translate("MainWindow", "список событий"))
        self.search_le.setToolTip(_translate("MainWindow", "<html><head/><body><p>строка поиска</p></body></html>"))
        self.refresh_btn.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>обновить список событий</p></body></html>"))
