# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(959, 295)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #040c0e;\n"
"}\n"
"\n"
"QFrame#frame {\n"
"    border-radius: 10px;\n"
"    background-color: #0a1215;\n"
"}\n"
"\n"
"QLabel#title {\n"
"    font-family: Verdana, Geneva, sans-serif;\n"
"    font-size: 40px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    font-variant: small-caps;\n"
"    text-transform: lowercase;\n"
"    border-radius: 20px;\n"
"    color: #be9063;\n"
"}\n"
"QLabel#title:hover {\n"
"    color: #F3E0D2;\n"
"}\n"
"\n"
"QPushButton#confirm_btn, QPushButton#color_btn, QPushButton#delete_now {\n"
"    font-family: Verdana, Geneva, sans-serif;\n"
"    font-size: 20px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    font-variant: small-caps;\n"
"    text-transform: lowercase;\n"
"    background-color: #132226;\n"
"    color: #a4978e;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton#confirm_btn:hover, QPushButton#color_btn:hover, QPushButton#delete_now:hover {\n"
"    background-color: #525b56;\n"
"    color: #a4978e;\n"
"}\n"
"QPushButton#delete_now:hover {\n"
"    color: #a4978e;\n"
"    background-color: #602828;\n"
"}\n"
"\n"
"QLabel#label, QLabel#label_2 {\n"
"    font-family: Verdana, Geneva, sans-serif;\n"
"    font-size: 20px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    color: #525b56;\n"
"    font-variant: small-caps;\n"
"    text-transform: lowercase;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #525b56;\n"
"    color: #a4978e;\n"
"    border-radius: 10px;\n"
"    font-family: Verdana, Geneva, sans-serif;\n"
"    font-size: 20px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    opacity: 0.6;\n"
"    padding: 5px;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: #828a86;\n"
"    color: #132226;\n"
"    opacity: 1;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(-1, 11, -1, -1)
        self.gridLayout.setVerticalSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 0, 1, 1)
        self.name_le = QtWidgets.QLineEdit(self.frame)
        self.name_le.setMinimumSize(QtCore.QSize(0, 30))
        self.name_le.setText("")
        self.name_le.setObjectName("name_le")
        self.gridLayout.addWidget(self.name_le, 6, 1, 1, 2)
        self.color_le = QtWidgets.QLineEdit(self.frame)
        self.color_le.setMinimumSize(QtCore.QSize(0, 30))
        self.color_le.setText("")
        self.color_le.setObjectName("color_le")
        self.gridLayout.addWidget(self.color_le, 5, 1, 1, 1)
        self.title = QtWidgets.QLabel(self.frame)
        self.title.setMaximumSize(QtCore.QSize(16777215, 50))
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.gridLayout.addWidget(self.title, 0, 0, 1, 2)
        self.color_btn = QtWidgets.QPushButton(self.frame)
        self.color_btn.setMinimumSize(QtCore.QSize(50, 40))
        self.color_btn.setMaximumSize(QtCore.QSize(50, 50))
        self.color_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.color_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../icons/color-palette.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.color_btn.setIcon(icon)
        self.color_btn.setObjectName("color_btn")
        self.gridLayout.addWidget(self.color_btn, 5, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.confirm_btn = QtWidgets.QPushButton(self.centralwidget)
        self.confirm_btn.setMinimumSize(QtCore.QSize(40, 40))
        self.confirm_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.confirm_btn.setObjectName("confirm_btn")
        self.verticalLayout.addWidget(self.confirm_btn)
        self.delete_now = QtWidgets.QPushButton(self.centralwidget)
        self.delete_now.setMinimumSize(QtCore.QSize(0, 40))
        self.delete_now.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_now.setObjectName("delete_now")
        self.verticalLayout.addWidget(self.delete_now)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "изменить цвет"))
        self.title.setText(_translate("MainWindow", "Настройки события"))
        self.label_2.setText(_translate("MainWindow", "изменить название"))
        self.confirm_btn.setText(_translate("MainWindow", "применить"))
        self.delete_now.setText(_translate("MainWindow", "удалить"))
