# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_time_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(882, 149)
        Form.setStyleSheet("QLabel {\n"
"    font-family: Verdana, Geneva, sans-serif;\n"
"    font-size: 40px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    color: #be9063;\n"
"    font-variant: small-caps;\n"
"    text-transform: lowercase;\n"
"    border-radius: 20px;\n"
"    background-color: #040c0e;\n"
"}\n"
"QLabel:hover {\n"
"    color: #F3E0D2;\n"
"}\n"
"\n"
"QPushButton {\n"
"    font-family: Verdana, Geneva, sans-serif;\n"
"    font-size: 20px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    font-weight: normal;\n"
"    text-decoration: none;\n"
"    font-style: normal;\n"
"    font-variant: small-caps;\n"
"    text-transform: lowercase;\n"
"    background-color: #132226;\n"
"    color: #a4978e;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #525b56;\n"
"    color: #a4978e;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QFrame#fr {\n"
"    font-family: Verdana, Geneva, sans-serif;\n"
"    font-size: 30px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    font-weight: normal;\n"
"    text-decoration: none;\n"
"    font-style: normal;\n"
"    font-variant: small-caps;\n"
"    text-transform: lowercase;\n"
"    background-color: #132226;\n"
"    color: #828a86;\n"
"    border-radius: 30px;\n"
"}\n"
"QLabel#title {\n"
"    color: #828a86;\n"
"    border-radius: 20px;\n"
"}\n"
"QFrame#color_frame {\n"
"    background-color: #be9063;\n"
"    color: #828a86;\n"
"    border-radius: 20px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fr = QtWidgets.QFrame(Form)
        self.fr.setMinimumSize(QtCore.QSize(860, 0))
        self.fr.setMaximumSize(QtCore.QSize(16777215, 127))
        self.fr.setStyleSheet("")
        self.fr.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr.setObjectName("fr")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.fr)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.time_ymd_2 = QtWidgets.QLabel(self.fr)
        self.time_ymd_2.setAlignment(QtCore.Qt.AlignCenter)
        self.time_ymd_2.setObjectName("time_ymd_2")
        self.gridLayout_2.addWidget(self.time_ymd_2, 1, 0, 1, 1)
        self.title = QtWidgets.QLabel(self.fr)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.gridLayout_2.addWidget(self.title, 0, 0, 1, 2)
        self.settings_btn_2 = QtWidgets.QPushButton(self.fr)
        self.settings_btn_2.setMinimumSize(QtCore.QSize(50, 50))
        self.settings_btn_2.setMaximumSize(QtCore.QSize(50, 50))
        self.settings_btn_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings_btn_2.setIcon(icon)
        self.settings_btn_2.setIconSize(QtCore.QSize(40, 40))
        self.settings_btn_2.setObjectName("settings_btn_2")
        self.gridLayout_2.addWidget(self.settings_btn_2, 1, 2, 1, 1)
        self.color_frame = QtWidgets.QFrame(self.fr)
        self.color_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.color_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.color_frame.setObjectName("color_frame")
        self.gridLayout_2.addWidget(self.color_frame, 0, 2, 1, 1)
        self.time_hms_2 = QtWidgets.QLabel(self.fr)
        self.time_hms_2.setAlignment(QtCore.Qt.AlignCenter)
        self.time_hms_2.setObjectName("time_hms_2")
        self.gridLayout_2.addWidget(self.time_hms_2, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.fr)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.time_ymd_2.setToolTip(_translate("Form", "<html><head/><body><p>гг.мм.дд</p></body></html>"))
        self.time_ymd_2.setText(_translate("Form", "0000 / 00 / 00"))
        self.title.setText(_translate("Form", "event"))
        self.time_hms_2.setToolTip(_translate("Form", "<html><head/><body><p>чч.мм.сс</p></body></html>"))
        self.time_hms_2.setText(_translate("Form", "00 : 00 : 00"))
