# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_timer_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(923, 601)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #040c0e;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-family: Verdana, Geneva, sans-serif;\n"
"    font-size: 40px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    color: #be9063;\n"
"}\n"
"QLabel:hover {\n"
"    font-size: 40px;\n"
"    letter-spacing: 2px;\n"
"    word-spacing: 6px;\n"
"    color: #F3E0D2;\n"
"}\n"
"QFrame#frame_2 {\n"
"    background-color: #040c0e;\n"
"    border: 2px solid #be9063;\n"
"    border-radius: 20px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.hms_lbl = QtWidgets.QLabel(self.frame_2)
        self.hms_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.hms_lbl.setObjectName("hms_lbl")
        self.gridLayout.addWidget(self.hms_lbl, 4, 2, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 221, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 5, 1, 1, 4)
        self.event_name_lbl = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.event_name_lbl.sizePolicy().hasHeightForWidth())
        self.event_name_lbl.setSizePolicy(sizePolicy)
        self.event_name_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.event_name_lbl.setObjectName("event_name_lbl")
        self.gridLayout.addWidget(self.event_name_lbl, 1, 1, 1, 4)
        spacerItem2 = QtWidgets.QSpacerItem(241, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 4, 2, 1)
        spacerItem3 = QtWidgets.QSpacerItem(241, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 1, 2, 1)
        self.days_lbl = QtWidgets.QLabel(self.frame_2)
        self.days_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.days_lbl.setObjectName("days_lbl")
        self.gridLayout.addWidget(self.days_lbl, 3, 2, 1, 2)
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Большой таймер"))
        self.hms_lbl.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt;\">[часов] : [минут] : [секунд]</span></p></body></html>"))
        self.hms_lbl.setText(_translate("MainWindow", "00 : 00 : 00"))
        self.event_name_lbl.setText(_translate("MainWindow", "событие"))
        self.days_lbl.setToolTip(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Verdana,Geneva,sans-serif\'; font-size:40px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">[дней] / [месяцев] / [лет]</span></p></body></html>"))
        self.days_lbl.setText(_translate("MainWindow", "0"))
